CREATE TABLE `TEQIP_PACKAGE`(
  `PACKAGE_ID` int(5) NOT NULL AUTO_INCREMENT,
  `PROCUREMENT_PLAN_ID` int NOT NULL,
  `PACKAGE_CODE` varchar(50) DEFAULT NULL,
  `PACKAGE_NAME` varchar(50) DEFAULT NULL,
  `JUSTIFICATION` varchar(1000) DEFAULT NULL,
  `CATEGORY_ID` int DEFAULT NULL,
  `SUB_CATEGORY_ID` int DEFAULT NULL,
  `ACTIVITY_ID` int DEFAULT NULL,
  `FINANCIAL_SANCTION_DATE` date DEFAULT NULL,
  `ISPROP` tinyint(4) DEFAULT NULL,
  `ISGEM` tinyint(4) DEFAULT NULL,
  `ISCOE` tinyint(4) DEFAULT NULL,
  `PROCUREMENT_METHOD_ID` int NOT NULL,
  `SERVICE_PROVIDER_ID` int DEFAULT NULL,
  `ESTIMATED_COST` float DEFAULT NULL,
  `REVISION_COMMENTS` varchar(30) DEFAULT NULL,
   INSTITUTION_ID  int DEFAULT NULL,
   SPFUID int DEFAULT NULL,
   TYPEOFPLAN_CREATOR int NOT NULL,
   PROCUREMENTSTAGEID int NOT NULL,   
   REVISEID int NOT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  PRIMARY KEY (`PACKAGE_ID`),
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),
  FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES TEQIP_SUBCATEGORYMASTER(SUBCAT_ID),
  FOREIGN KEY (ACTIVITY_ID) REFERENCES TEQIP_ACTIVITIYMASTER(ACTIVITY_ID),
  FOREIGN KEY (PROCUREMENT_METHOD_ID) REFERENCES TEQIP_PROCUREMENTMETHOD(PROCUREMENTMETHOD_ID),
  FOREIGN KEY (PROCUREMENT_PLAN_ID) REFERENCES TEQIP_PROCUREMENTMASTER(PROCUREMENTMASTER_ID),
  FOREIGN KEY (INSTITUTION_ID) REFERENCES TEQIP_INSTITUTIONS(INSTITUTION_ID),
  FOREIGN KEY (PROCUREMENTSTAGEID) REFERENCES TEQIP_PMSS_PROCUREMENTSTAGES(PROCUREMENTSTAGEID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TEQIP_PACKAGE_HISTORY`(
  `PACKAGE_ID` int(5) NOT NULL AUTO_INCREMENT,
  `PROCUREMENT_PLAN_ID` int NOT NULL,
  `PACKAGE_CODE` varchar(50) DEFAULT NULL,
  `PACKAGE_NAME` varchar(50) DEFAULT NULL,
  `JUSTIFICATION` varchar(1000) DEFAULT NULL,
  `CATEGORY_ID` int DEFAULT NULL,
  `SUB_CATEGORY_ID` int DEFAULT NULL,
  `ACTIVITY_ID` int DEFAULT NULL,
  `FINANCIAL_SANCTION_DATE` date DEFAULT NULL,
  `ISPROP` tinyint(4) DEFAULT NULL,
  `ISGEM` tinyint(4) DEFAULT NULL,
  `ISCOE` tinyint(4) DEFAULT NULL,
  `PROCUREMENT_METHOD_ID` int NOT NULL,
  `SERVICE_PROVIDER_ID` int DEFAULT NULL,
  `ESTIMATED_COST` float DEFAULT NULL,
  `REVISION_COMMENTS` varchar(30) DEFAULT NULL,
   INSTITUTION_ID  int NOT NULL,
   SPFUID int DEFAULT NULL,
   TYPEOFPLAN_CREATOR int NOT NULL,
   PROCUREMENTSTAGEID int NOT NULL,
   REVISEID int NOT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  PRIMARY KEY (`PACKAGE_ID`),
  FOREIGN KEY (CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),
  FOREIGN KEY (SUB_CATEGORY_ID) REFERENCES TEQIP_SUBCATEGORYMASTER(SUBCAT_ID),
  FOREIGN KEY (ACTIVITY_ID) REFERENCES TEQIP_ACTIVITIYMASTER(ACTIVITY_ID),
  FOREIGN KEY (PROCUREMENT_METHOD_ID) REFERENCES TEQIP_PROCUREMENTMETHOD(PROCUREMENTMETHOD_ID),
  FOREIGN KEY (PROCUREMENT_PLAN_ID) REFERENCES TEQIP_PROCUREMENTMASTER(PROCUREMENTMASTER_ID),
  FOREIGN KEY (INSTITUTION_ID) REFERENCES TEQIP_INSTITUTIONS(INSTITUTION_ID),
  FOREIGN KEY (SPFUID) REFERENCES TEQIP_STATEMASTER(STATE_ID),
  FOREIGN KEY (PROCUREMENTSTAGEID) REFERENCES TEQIP_PMSS_PROCUREMENTSTAGES(PROCUREMENTSTAGEID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `TEQIP_ITEM_GOODS_DETAIL`(
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(5) DEFAULT NULL,
  `ITEM_SPECIFICATION` varchar(500) DEFAULT NULL,
  `ITEM_CATEGORY_ID` int NOT NULL,
  `ITEM_QNT` float DEFAULT NULL,
  `ITEM_COST_UNIT` float DEFAULT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  `PACKAGE_ID` int NOT NULL,
   REVISEID int NOT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES TEQIP_ITEM_MASTER(ITEM_ID),
  FOREIGN KEY (PACKAGE_ID) REFERENCES TEQIP_PACKAGE(PACKAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `TEQIP_ITEM_GOODS_DETAIL_HISTORY`(
 `ID` int(5) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(5) DEFAULT NULL,
  `ITEM_SPECIFICATION` varchar(500) DEFAULT NULL,
  `ITEM_CATEGORY_ID` int NOT NULL,
  `ITEM_QNT` float DEFAULT NULL,
  `ITEM_COST_UNIT` float DEFAULT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  `PACKAGE_ID` int NOT NULL,
   REVISEID int NOT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (ITEM_CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES TEQIP_ITEM_MASTER(ITEM_ID),
  FOREIGN KEY (PACKAGE_ID) REFERENCES TEQIP_PACKAGE(PACKAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE  `TEQIP_ITEM_WORK_DETAIL`(
  `ID` int NOT NULL AUTO_INCREMENT,
  `WORK_NAME` varchar(500) DEFAULT NULL,
  `WORK_SPECIFICATION` varchar(500) DEFAULT NULL,
  `WORK_CATEGORY_ID` int NOT NULL,
  `WORK_COST` float DEFAULT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  `PACKAGE_ID` int DEFAULT NULL,
   REVISEID int NOT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (WORK_CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),  
  FOREIGN KEY (PACKAGE_ID) REFERENCES TEQIP_PACKAGE(PACKAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE  `TEQIP_ITEM_WORK_DETAIL_HISTORY`(
   `ID` int NOT NULL AUTO_INCREMENT,
  `WORK_NAME` varchar(500) DEFAULT NULL,
  `WORK_SPECIFICATION` varchar(500) DEFAULT NULL,
  `WORK_CATEGORY_ID` int NOT NULL,
  `WORK_COST` float DEFAULT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
  `PACKAGE_ID` int DEFAULT NULL,
   REVISEID int NOT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (WORK_CATEGORY_ID) REFERENCES TEQIP_CATEGORYMASTER(CAT_ID),  
  FOREIGN KEY (PACKAGE_ID) REFERENCES TEQIP_PACKAGE(PACKAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




CREATE TABLE `TEQIP_PLAN_APPROVALSTATUS`(
  `ID` int NOT NULL AUTO_INCREMENT,
   TEQIP_PLANAPPROVAL_ID int NOT NULL,
  `PROCUREMENT_PLAN_ID` int NOT NULL,
  `PACKAGE_ID` int NOT NULL,
   INSTITUTION_ID  int NOT NULL,
   SPFUID  int NOT NULL,
   CREATED_TYPE int NOT NULL,
   PROCUREMENTSTAGEID int NOT NULL,
   REVISEID int NOT NULL,
  `CREATED_ON` TIMESTAMP DEFAULT NOW(),
  `CREATED_BY` int DEFAULT NULL,
  `MODIFY_ON` date DEFAULT NULL,
  `MODIFY_BY` int DEFAULT NULL,
	  PRIMARY KEY (`ID`),
	  FOREIGN KEY (PROCUREMENT_PLAN_ID) REFERENCES TEQIP_PROCUREMENTMASTER(PROCUREMENTMASTER_ID),
	  FOREIGN KEY (PACKAGE_ID) REFERENCES TEQIP_PACKAGE(PACKAGE_ID),
	  FOREIGN KEY (INSTITUTION_ID) REFERENCES TEQIP_INSTITUTIONS(INSTITUTION_ID),
	  FOREIGN KEY (SPFUID) REFERENCES TEQIP_STATEMASTER(STATE_ID),
	  FOREIGN KEY (PROCUREMENTSTAGEID) REFERENCES TEQIP_PMSS_PROCUREMENTSTAGES(PROCUREMENTSTAGEID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;